services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=bd_minafro
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=minafro123
    ports:
      - "5432:5432"
    networks:
      - prisma-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prisma -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  # ------------------------
  # Prisma Migration Service (one-time)
  # ------------------------
  migrate:
    container_name: migrate
    build:
      context: .
    command: |
      sh -c "
        npx prisma migrate deploy && npx prisma db seed
      "
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  # ------------------------
  # Express API Server
  # ------------------------
  express-api:
    container_name: express-api
    build:
      context: .
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://usuario:minafro123@postgres:5432/bd_minafro
    #volumes:
    #  - /express-api:/app # Monta el directorio del proyecto en el contenedor
    #  - node_modules:/app/node_modules # Monta node_modules para persistencia
    #command: |
    #  sh -c "
    #    ls -la 
    #    echo 'Comando test...'
    #  "
    
networks:
  prisma-network:

volumes:
  postgres_data: