services:
  postgresdb:
    image: postgres:15
    container_name: postgresdb
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: minafro123
      POSTGRES_DB: bd_minafro
    ports:
      - "5432:5432"
  express-api:
    build:
      context: .
    container_name: express-api
    restart: always
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - postgresdb
    environment:
      DATABASE_URL: postgres://usuario:minafro123@postgresdb:5432/bd_minafro
    #volumes:
    #  - /express-api:/app # Monta el directorio del proyecto en el contenedor
    #  - node_modules:/app/node_modules # Monta node_modules para persistencia
    command: |
      sh -c "
        ls -la 
        echo 'Comando test...'
        npm install express --save
        npm run dev
      "
volumes:
  postgres_data:
    driver: local